default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: gabriel
  password: 123456

development:
  <<: *default
  database: gblog_development

production:
  <<: *default
  database: gblog_production

test:
  <<: *default
  host: localhost
  database: db/gblog_test
  password: 123456